FROM golang:1.21

# Build: docker build -t sliver -f Dockerfile.sliver .
# Run:
#    $ mkdir sliver-config
#    $ docker run -p 80:80 -p 53:53 -p 443:443 -p 31337:31337 -v $PWD/sliver-config:/home/sliver/.sliver-client/configs -name sliver sliver

ENV PROTOC_VER 21.12
ENV PROTOC_GEN_GO_VER v1.27.1
ENV GRPC_GO v1.2.0

# Base packages
RUN apt-get update --fix-missing && apt-get -y install \
    git build-essential zlib1g zlib1g-dev \
    libxml2 libxml2-dev libxslt-dev locate curl \
    libreadline6-dev libcurl4-openssl-dev git-core \
    libssl-dev libyaml-dev openssl autoconf libtool \
    ncurses-dev bison curl wget xsel postgresql \
    postgresql-contrib postgresql-client libpq-dev \
    libapr1 libaprutil1 libsvn1 \
    libpcap-dev libsqlite3-dev libgmp3-dev \
    zip unzip mingw-w64 binutils-mingw-w64 g++-mingw-w64 \
    nasm gcc-multilib

#
# > User
#
RUN groupadd -g 999 sliver && useradd -r -u 999 -g sliver sliver
RUN mkdir -p /home/sliver/ && chown -R sliver:sliver /home/sliver

#
# > Metasploit
#
RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall \
    && chmod 755 msfinstall \
    && ./msfinstall
RUN mkdir -p ~/.msf4/ && touch ~/.msf4/initial_setup_complete \
    &&  su -l sliver -c 'mkdir -p ~/.msf4/ && touch ~/.msf4/initial_setup_complete'

RUN cd /opt && curl -s https://api.github.com/repos/BishopFox/sliver/releases/latest | grep ".*browser_download_url.*_linux\"" | cut -d : -f 2,3 | tr -d \"  | wget -qi -
RUN mv /opt/sliver-server_linux /opt/sliver-server && mv /opt/sliver-client_linux /opt/sliver-client && chmod +x /opt/sliver*

Add sliverentry.sh /sliverentry.sh
RUN chmod +x /sliverentry.sh

VOLUME /home/sliver/.sliver-client
VOLUME /home/sliver/.sliver
USER sliver
WORKDIR /home/sliver/

RUN /opt/sliver-server unpack

EXPOSE 53 80 443 31337
STOPSIGNAL SIGQUIT
ENTRYPOINT [ "/sliverentry.sh" ]
