From kalilinux/kali-rolling

LABEL maintainer="wolfgang.hotwagner@ait.ac.at"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y metasploit-framework

CMD /usr/bin/msfrpcd -f -P hacker
