# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attackmate_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'attackmate_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import playbook_pb2 as playbook__pb2
import command_pb2 as command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61ttackmate_service.proto\x12\x11\x61ttackmate.remote\x1a\x0eplaybook.proto\x1a\rcommand.proto2\xe4\x01\n\x11\x41ttackMateService\x12h\n\x0f\x45xecutePlaybook\x12).attackmate.remote.ExecutePlaybookRequest\x1a*.attackmate.remote.ExecutePlaybookResponse\x12\x65\n\x0e\x45xecuteCommand\x12(.attackmate.remote.ExecuteCommandRequest\x1a).attackmate.remote.ExecuteCommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attackmate_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTACKMATESERVICE']._serialized_start=79
  _globals['_ATTACKMATESERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
