# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import command_pb2 as command__pb2
from . import playbook_pb2 as playbook__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in attackmate_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttackMateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePlaybook = channel.unary_unary(
                '/attackmate.remote.AttackMateService/ExecutePlaybook',
                request_serializer=playbook__pb2.ExecutePlaybookRequest.SerializeToString,
                response_deserializer=playbook__pb2.ExecutePlaybookResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/attackmate.remote.AttackMateService/ExecuteCommand',
                request_serializer=command__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=command__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)


class AttackMateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePlaybook(self, request, context):
        """Executes an entire playbook provided as YAML content
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Executes a single command TODO: (server maintains state)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttackMateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePlaybook': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlaybook,
                    request_deserializer=playbook__pb2.ExecutePlaybookRequest.FromString,
                    response_serializer=playbook__pb2.ExecutePlaybookResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=command__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=command__pb2.ExecuteCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'attackmate.remote.AttackMateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('attackmate.remote.AttackMateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttackMateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePlaybook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attackmate.remote.AttackMateService/ExecutePlaybook',
            playbook__pb2.ExecutePlaybookRequest.SerializeToString,
            playbook__pb2.ExecutePlaybookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/attackmate.remote.AttackMateService/ExecuteCommand',
            command__pb2.ExecuteCommandRequest.SerializeToString,
            command__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
