# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x11\x61ttackmate.remote\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0c\x63ommon.proto\"\xc2\x04\n\x07\x43ommand\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12+\n\nparameters\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x14\n\x07only_if\x18\n \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x65rror_if\x18\x0b \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0c\x65rror_if_not\x18\x0c \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07loop_if\x18\r \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bloop_if_not\x18\x0e \x01(\tH\x04\x88\x01\x01\x12\x17\n\nloop_count\x18\x0f \x01(\tH\x05\x88\x01\x01\x12\x1a\n\rexit_on_error\x18\x10 \x01(\x08H\x06\x88\x01\x01\x12\x11\n\x04save\x18\x11 \x01(\tH\x07\x88\x01\x01\x12\x17\n\nbackground\x18\x12 \x01(\x08H\x08\x88\x01\x01\x12\x19\n\x0ckill_on_exit\x18\x13 \x01(\x08H\t\x88\x01\x01\x12:\n\x08metadata\x18\x14 \x03(\x0b\x32(.attackmate.remote.Command.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_only_ifB\x0b\n\t_error_ifB\x0f\n\r_error_if_notB\n\n\x08_loop_ifB\x0e\n\x0c_loop_if_notB\r\n\x0b_loop_countB\x10\n\x0e_exit_on_errorB\x07\n\x05_saveB\r\n\x0b_backgroundB\x0f\n\r_kill_on_exit\"D\n\x15\x45xecuteCommandRequest\x12+\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1a.attackmate.remote.Command\"\x88\x01\n\x16\x45xecuteCommandResponse\x12\x30\n\x06result\x18\x01 \x01(\x0b\x32 .attackmate.remote.CommandResult\x12<\n\rupdated_state\x18\x02 \x01(\x0b\x32%.attackmate.remote.VariableStoreStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_METADATAENTRY']._loaded_options = None
  _globals['_COMMAND_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_COMMAND']._serialized_start=81
  _globals['_COMMAND']._serialized_end=659
  _globals['_COMMAND_METADATAENTRY']._serialized_start=468
  _globals['_COMMAND_METADATAENTRY']._serialized_end=515
  _globals['_EXECUTECOMMANDREQUEST']._serialized_start=661
  _globals['_EXECUTECOMMANDREQUEST']._serialized_end=729
  _globals['_EXECUTECOMMANDRESPONSE']._serialized_start=732
  _globals['_EXECUTECOMMANDRESPONSE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
