# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: father_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'father_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61ther_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\x90\x04\n\x12\x46\x61therCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x10\n\x03gid\x18\x64 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07srcport\x18\x65 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tepochtime\x18\x66 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07\x65nv_var\x18g \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0b\x66ile_prefix\x18h \x01(\tH\x04\x88\x01\x01\x12\x19\n\x0cpreload_file\x18i \x01(\tH\x05\x88\x01\x01\x12\x17\n\nhiddenport\x18j \x01(\tH\x06\x88\x01\x01\x12\x17\n\nshell_pass\x18k \x01(\tH\x07\x88\x01\x01\x12\x19\n\x0cinstall_path\x18l \x01(\tH\x08\x88\x01\x01\x12\x17\n\nlocal_path\x18m \x01(\tH\t\x88\x01\x01\x12\x11\n\x04\x61rch\x18n \x01(\tH\n\x88\x01\x01\x12\x1a\n\rbuild_command\x18o \x01(\tH\x0b\x88\x01\x01\x42\x06\n\x04_gidB\n\n\x08_srcportB\x0c\n\n_epochtimeB\n\n\x08_env_varB\x0e\n\x0c_file_prefixB\x0f\n\r_preload_fileB\r\n\x0b_hiddenportB\r\n\x0b_shell_passB\x0f\n\r_install_pathB\r\n\x0b_local_pathB\x07\n\x05_archB\x10\n\x0e_build_commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'father_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FATHERCOMMANDPROTO']._serialized_start=64
  _globals['_FATHERCOMMANDPROTO']._serialized_end=592
# @@protoc_insertion_point(module_scope)
