# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http_client_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'http_client_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19http_client_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xa4\x05\n\x16HttpClientCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x0b\n\x03url\x18\x65 \x01(\t\x12\x1b\n\x0eoutput_headers\x18\x66 \x01(\x08H\x00\x88\x01\x01\x12G\n\x07headers\x18g \x03(\x0b\x32\x36.attackmate.remote.HttpClientCommandProto.HeadersEntry\x12G\n\x07\x63ookies\x18h \x03(\x0b\x32\x36.attackmate.remote.HttpClientCommandProto.CookiesEntry\x12\x41\n\x04\x64\x61ta\x18i \x03(\x0b\x32\x33.attackmate.remote.HttpClientCommandProto.DataEntry\x12\x17\n\nlocal_path\x18j \x01(\tH\x01\x88\x01\x01\x12\x16\n\tuseragent\x18k \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06\x66ollow\x18l \x01(\x08H\x03\x88\x01\x01\x12\x13\n\x06verify\x18m \x01(\x08H\x04\x88\x01\x01\x12\x12\n\x05http2\x18n \x01(\x08H\x05\x88\x01\x01\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0c\x43ookiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x11\n\x0f_output_headersB\r\n\x0b_local_pathB\x0c\n\n_useragentB\t\n\x07_followB\t\n\x07_verifyB\x08\n\x06_http2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'http_client_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HTTPCLIENTCOMMANDPROTO_HEADERSENTRY']._loaded_options = None
  _globals['_HTTPCLIENTCOMMANDPROTO_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_HTTPCLIENTCOMMANDPROTO_COOKIESENTRY']._loaded_options = None
  _globals['_HTTPCLIENTCOMMANDPROTO_COOKIESENTRY']._serialized_options = b'8\001'
  _globals['_HTTPCLIENTCOMMANDPROTO_DATAENTRY']._loaded_options = None
  _globals['_HTTPCLIENTCOMMANDPROTO_DATAENTRY']._serialized_options = b'8\001'
  _globals['_HTTPCLIENTCOMMANDPROTO']._serialized_start=69
  _globals['_HTTPCLIENTCOMMANDPROTO']._serialized_end=745
  _globals['_HTTPCLIENTCOMMANDPROTO_HEADERSENTRY']._serialized_start=526
  _globals['_HTTPCLIENTCOMMANDPROTO_HEADERSENTRY']._serialized_end=572
  _globals['_HTTPCLIENTCOMMANDPROTO_COOKIESENTRY']._serialized_start=574
  _globals['_HTTPCLIENTCOMMANDPROTO_COOKIESENTRY']._serialized_end=620
  _globals['_HTTPCLIENTCOMMANDPROTO_DATAENTRY']._serialized_start=622
  _globals['_HTTPCLIENTCOMMANDPROTO_DATAENTRY']._serialized_end=665
# @@protoc_insertion_point(module_scope)
