# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: json_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'json_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12json_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xac\x01\n\x10JsonCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x10\n\x03\x63md\x18\x64 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nlocal_path\x18\x65 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08varstore\x18\x66 \x01(\x08H\x02\x88\x01\x01\x42\x06\n\x04_cmdB\r\n\x0b_local_pathB\x0b\n\t_varstoreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'json_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONCOMMANDPROTO']._serialized_start=62
  _globals['_JSONCOMMANDPROTO']._serialized_end=234
# @@protoc_insertion_point(module_scope)
