# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msf_payload_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'msf_payload_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19msf_payload_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xf0\x04\n\x16MsfPayloadCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x13\n\x06\x66ormat\x18\x65 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x62\x61\x64\x63hars\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0c\x66orce_encode\x18g \x01(\x08H\x02\x88\x01\x01\x12\x14\n\x07\x65ncoder\x18h \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08template\x18i \x01(\tH\x04\x88\x01\x01\x12\x15\n\x08platform\x18j \x01(\tH\x05\x88\x01\x01\x12\"\n\x15keep_template_working\x18k \x01(\x08H\x06\x88\x01\x01\x12\x19\n\x0cnopsled_size\x18l \x01(\tH\x07\x88\x01\x01\x12\x11\n\x04iter\x18m \x01(\tH\x08\x88\x01\x01\x12V\n\x0fpayload_options\x18n \x03(\x0b\x32=.attackmate.remote.MsfPayloadCommandProto.PayloadOptionsEntry\x12\x17\n\nlocal_path\x18o \x01(\tH\t\x88\x01\x01\x1a\x35\n\x13PayloadOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\t\n\x07_formatB\x0b\n\t_badcharsB\x0f\n\r_force_encodeB\n\n\x08_encoderB\x0b\n\t_templateB\x0b\n\t_platformB\x18\n\x16_keep_template_workingB\x0f\n\r_nopsled_sizeB\x07\n\x05_iterB\r\n\x0b_local_pathb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msf_payload_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSFPAYLOADCOMMANDPROTO_PAYLOADOPTIONSENTRY']._loaded_options = None
  _globals['_MSFPAYLOADCOMMANDPROTO_PAYLOADOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_MSFPAYLOADCOMMANDPROTO']._serialized_start=69
  _globals['_MSFPAYLOADCOMMANDPROTO']._serialized_end=693
  _globals['_MSFPAYLOADCOMMANDPROTO_PAYLOADOPTIONSENTRY']._serialized_start=494
  _globals['_MSFPAYLOADCOMMANDPROTO_PAYLOADOPTIONSENTRY']._serialized_end=547
# @@protoc_insertion_point(module_scope)
