# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msf_session_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'msf_session_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19msf_session_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xe6\x01\n\x16MsfSessionCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x13\n\x06stdapi\x18\x65 \x01(\x08H\x00\x88\x01\x01\x12\x12\n\x05write\x18\x66 \x01(\x08H\x01\x88\x01\x01\x12\x11\n\x04read\x18g \x01(\x08H\x02\x88\x01\x01\x12\x0f\n\x07session\x18h \x01(\t\x12\x14\n\x07\x65nd_str\x18i \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_stdapiB\x08\n\x06_writeB\x07\n\x05_readB\n\n\x08_end_strb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msf_session_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSFSESSIONCOMMANDPROTO']._serialized_start=69
  _globals['_MSFSESSIONCOMMANDPROTO']._serialized_end=299
# @@protoc_insertion_point(module_scope)
