# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msf_module_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'msf_module_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18msf_module_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xf4\x03\n\x15MsfModuleCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x13\n\x06target\x18\x65 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0f\x63reates_session\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07session\x18g \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07payload\x18h \x01(\tH\x03\x88\x01\x01\x12\x46\n\x07options\x18i \x03(\x0b\x32\x35.attackmate.remote.MsfModuleCommandProto.OptionsEntry\x12U\n\x0fpayload_options\x18j \x03(\x0b\x32<.attackmate.remote.MsfModuleCommandProto.PayloadOptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x35\n\x13PayloadOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\t\n\x07_targetB\x12\n\x10_creates_sessionB\n\n\x08_sessionB\n\n\x08_payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msf_module_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSFMODULECOMMANDPROTO_OPTIONSENTRY']._loaded_options = None
  _globals['_MSFMODULECOMMANDPROTO_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_MSFMODULECOMMANDPROTO_PAYLOADOPTIONSENTRY']._loaded_options = None
  _globals['_MSFMODULECOMMANDPROTO_PAYLOADOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_MSFMODULECOMMANDPROTO']._serialized_start=68
  _globals['_MSFMODULECOMMANDPROTO']._serialized_end=568
  _globals['_MSFMODULECOMMANDPROTO_OPTIONSENTRY']._serialized_start=412
  _globals['_MSFMODULECOMMANDPROTO_OPTIONSENTRY']._serialized_end=458
  _globals['_MSFMODULECOMMANDPROTO_PAYLOADOPTIONSENTRY']._serialized_start=460
  _globals['_MSFMODULECOMMANDPROTO_PAYLOADOPTIONSENTRY']._serialized_end=513
# @@protoc_insertion_point(module_scope)
