# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playbook.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'playbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaybook.proto\x12\x11\x61ttackmate.remote\x1a\x0c\x63ommon.proto\"m\n\x16\x45xecutePlaybookRequest\x12\x15\n\rplaybook_yaml\x18\x01 \x01(\t\x12<\n\rinitial_state\x18\x02 \x01(\x0b\x32%.attackmate.remote.VariableStoreState\"w\n\x17\x45xecutePlaybookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12:\n\x0b\x66inal_state\x18\x03 \x01(\x0b\x32%.attackmate.remote.VariableStoreStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEPLAYBOOKREQUEST']._serialized_start=51
  _globals['_EXECUTEPLAYBOOKREQUEST']._serialized_end=160
  _globals['_EXECUTEPLAYBOOKRESPONSE']._serialized_start=162
  _globals['_EXECUTEPLAYBOOKRESPONSE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
