# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: regex_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'regex_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13regex_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xa1\x02\n\x11RegExCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x14\n\x07replace\x18\x65 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04mode\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05input\x18g \x01(\tH\x02\x88\x01\x01\x12@\n\x06output\x18h \x03(\x0b\x32\x30.attackmate.remote.RegExCommandProto.OutputEntry\x1a-\n\x0bOutputEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_replaceB\x07\n\x05_modeB\x08\n\x06_inputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'regex_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGEXCOMMANDPROTO_OUTPUTENTRY']._loaded_options = None
  _globals['_REGEXCOMMANDPROTO_OUTPUTENTRY']._serialized_options = b'8\001'
  _globals['_REGEXCOMMANDPROTO']._serialized_start=63
  _globals['_REGEXCOMMANDPROTO']._serialized_end=352
  _globals['_REGEXCOMMANDPROTO_OUTPUTENTRY']._serialized_start=276
  _globals['_REGEXCOMMANDPROTO_OUTPUTENTRY']._serialized_end=321
# @@protoc_insertion_point(module_scope)
