# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shell_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shell_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from. import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13shell_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xe8\x02\n\x11ShellCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x18\n\x0binteractive\x18\x65 \x01(\x08H\x00\x88\x01\x01\x12\x1c\n\x0f\x63reates_session\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07session\x18g \x01(\tH\x02\x88\x01\x01\x12\x1c\n\x0f\x63ommand_timeout\x18h \x01(\tH\x03\x88\x01\x01\x12\x1a\n\rcommand_shell\x18j \x01(\tH\x04\x88\x01\x01\x12\x10\n\x03\x62in\x18k \x01(\x08H\x05\x88\x01\x01\x12\x11\n\x04read\x18l \x01(\x08H\x06\x88\x01\x01\x42\x0e\n\x0c_interactiveB\x12\n\x10_creates_sessionB\n\n\x08_sessionB\x12\n\x10_command_timeoutB\x10\n\x0e_command_shellB\x06\n\x04_binB\x07\n\x05_readb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shell_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHELLCOMMANDPROTO']._serialized_start=63
  _globals['_SHELLCOMMANDPROTO']._serialized_end=423
# @@protoc_insertion_point(module_scope)
