# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sliver_generate_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sliver_generate_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsliver_generate_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xed\x02\n\x1aSliverGenerateCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x13\n\x06target\x18\x64 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x63\x32url\x18\x65 \x01(\t\x12\x13\n\x06\x66ormat\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x0c\n\x04name\x18g \x01(\t\x12\x15\n\x08\x66ilepath\x18h \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08IsBeacon\x18i \x01(\x08H\x03\x88\x01\x01\x12\x1b\n\x0e\x42\x65\x61\x63onInterval\x18j \x01(\tH\x04\x88\x01\x01\x12\x16\n\tRunAtLoad\x18k \x01(\x08H\x05\x88\x01\x01\x12\x14\n\x07\x45vasion\x18l \x01(\x08H\x06\x88\x01\x01\x42\t\n\x07_targetB\t\n\x07_formatB\x0b\n\t_filepathB\x0b\n\t_IsBeaconB\x11\n\x0f_BeaconIntervalB\x0c\n\n_RunAtLoadB\n\n\x08_Evasionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sliver_generate_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SLIVERGENERATECOMMANDPROTO']._serialized_start=73
  _globals['_SLIVERGENERATECOMMANDPROTO']._serialized_end=438
# @@protoc_insertion_point(module_scope)
