# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sliver_listener_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sliver_listener_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsliver_listener_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xf4\x03\n\x1aSliverListenerCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x11\n\x04host\x18\x64 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x65 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x64omain\x18\x66 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07website\x18g \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04\x61\x63me\x18h \x01(\x08H\x04\x88\x01\x01\x12\x17\n\npersistent\x18i \x01(\x08H\x05\x88\x01\x01\x12\x18\n\x0b\x65nforce_otp\x18j \x01(\x08H\x06\x88\x01\x01\x12\x1b\n\x0erandomize_jarm\x18k \x01(\x08H\x07\x88\x01\x01\x12\x1e\n\x11long_poll_timeout\x18l \x01(\tH\x08\x88\x01\x01\x12\x1d\n\x10long_poll_jitter\x18m \x01(\tH\t\x88\x01\x01\x12\x14\n\x07timeout\x18n \x01(\tH\n\x88\x01\x01\x42\x07\n\x05_hostB\x07\n\x05_portB\t\n\x07_domainB\n\n\x08_websiteB\x07\n\x05_acmeB\r\n\x0b_persistentB\x0e\n\x0c_enforce_otpB\x11\n\x0f_randomize_jarmB\x14\n\x12_long_poll_timeoutB\x13\n\x11_long_poll_jitterB\n\n\x08_timeoutb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sliver_listener_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SLIVERLISTENERCOMMANDPROTO']._serialized_start=73
  _globals['_SLIVERLISTENERCOMMANDPROTO']._serialized_end=573
# @@protoc_insertion_point(module_scope)
