# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ssh_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ssh_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ssh_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xd1\x05\n\x0fSSHCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x15\n\x08hostname\x18\x65 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08username\x18g \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08password\x18h \x01(\tH\x03\x88\x01\x01\x12\x17\n\npassphrase\x18i \x01(\tH\x04\x88\x01\x01\x12\x19\n\x0ckey_filename\x18j \x01(\tH\x05\x88\x01\x01\x12\x1c\n\x0f\x63reates_session\x18k \x01(\tH\x06\x88\x01\x01\x12\x14\n\x07session\x18l \x01(\tH\x07\x88\x01\x01\x12\x18\n\x0b\x63lear_cache\x18m \x01(\x08H\x08\x88\x01\x01\x12\x14\n\x07timeout\x18n \x01(\x01H\t\x88\x01\x01\x12\x19\n\x0cjmp_hostname\x18o \x01(\tH\n\x88\x01\x01\x12\x15\n\x08jmp_port\x18p \x01(\tH\x0b\x88\x01\x01\x12\x19\n\x0cjmp_username\x18q \x01(\tH\x0c\x88\x01\x01\x12\x18\n\x0binteractive\x18r \x01(\x08H\r\x88\x01\x01\x12\x1c\n\x0f\x63ommand_timeout\x18s \x01(\tH\x0e\x88\x01\x01\x12\x0f\n\x07prompts\x18t \x03(\t\x12\x10\n\x03\x62in\x18u \x01(\x08H\x0f\x88\x01\x01\x42\x0b\n\t_hostnameB\x07\n\x05_portB\x0b\n\t_usernameB\x0b\n\t_passwordB\r\n\x0b_passphraseB\x0f\n\r_key_filenameB\x12\n\x10_creates_sessionB\n\n\x08_sessionB\x0e\n\x0c_clear_cacheB\n\n\x08_timeoutB\x0f\n\r_jmp_hostnameB\x0b\n\t_jmp_portB\x0f\n\r_jmp_usernameB\x0e\n\x0c_interactiveB\x12\n\x10_command_timeoutB\x06\n\x04_binb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssh_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SSHCOMMANDPROTO']._serialized_start=61
  _globals['_SSHCOMMANDPROTO']._serialized_end=782
# @@protoc_insertion_point(module_scope)
