# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vnc_command.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vnc_command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_command_pb2 as base__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11vnc_command.proto\x12\x11\x61ttackmate.remote\x1a\x12\x62\x61se_command.proto\"\xbc\x04\n\x0fVncCommandProto\x12\x32\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.attackmate.remote.BaseCommandFields\x12\x0b\n\x03\x63md\x18\x64 \x01(\t\x12\x15\n\x08hostname\x18\x65 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x66 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07\x64isplay\x18g \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08password\x18h \x01(\tH\x03\x88\x01\x01\x12\x10\n\x03key\x18i \x01(\tH\x04\x88\x01\x01\x12\x12\n\x05input\x18j \x01(\tH\x05\x88\x01\x01\x12\x15\n\x08\x66ilename\x18k \x01(\tH\x06\x88\x01\x01\x12\x0e\n\x01x\x18l \x01(\x05H\x07\x88\x01\x01\x12\x0e\n\x01y\x18m \x01(\x05H\x08\x88\x01\x01\x12\x1c\n\x0f\x63reates_session\x18n \x01(\tH\t\x88\x01\x01\x12\x14\n\x07session\x18o \x01(\tH\n\x88\x01\x01\x12\x13\n\x06maxrms\x18p \x01(\x01H\x0b\x88\x01\x01\x12\x1b\n\x0e\x65xpect_timeout\x18q \x01(\x05H\x0c\x88\x01\x01\x12\x1f\n\x12\x63onnection_timeout\x18r \x01(\x05H\r\x88\x01\x01\x42\x0b\n\t_hostnameB\x07\n\x05_portB\n\n\x08_displayB\x0b\n\t_passwordB\x06\n\x04_keyB\x08\n\x06_inputB\x0b\n\t_filenameB\x04\n\x02_xB\x04\n\x02_yB\x12\n\x10_creates_sessionB\n\n\x08_sessionB\t\n\x07_maxrmsB\x11\n\x0f_expect_timeoutB\x15\n\x13_connection_timeoutb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vnc_command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VNCCOMMANDPROTO']._serialized_start=61
  _globals['_VNCCOMMANDPROTO']._serialized_end=633
# @@protoc_insertion_point(module_scope)
